class key_expansion():
    rounds = 10
    block_size = 128
    def RotWord():
        ...
    def SubWord(): #non linear
        #обратный элемент в GF(2^8)
        #аффинное преобразование 
        ...
    def Rcon():
        ... 
class Initial_Round():
    def AddRoundKey():
        ... 
class Main_Rounds():
    def SubBytes():
        ... 
    def ShiftRows():
        ... 
    def MixColumns():
        ... 
    def AddRoundKey():
        ...  